package manman.pro.db.domain;

import java.math.BigDecimal;
import java.time.LocalDateTime;

public class ShopOrder {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table shop_order
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    public static final Boolean NOT_DELETED = false;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table shop_order
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    @Deprecated
    public static final Boolean DEL_FLAG_ON = false;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table shop_order
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    public static final Boolean IS_DELETED = true;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table shop_order
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    @Deprecated
    public static final Boolean DEL_FLAG_OFF = true;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_order.id
     *
     * @mbg.generated Thu Jun 28 18:05:45 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_order.user_id
     *
     * @mbg.generated Thu Jun 28 18:05:45 CST 2018
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_order.order_sn
     *
     * @mbg.generated Thu Jun 28 18:05:45 CST 2018
     */
    private String orderSn;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_order.order_status
     *
     * @mbg.generated Thu Jun 28 18:05:45 CST 2018
     */
    private Short orderStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_order.consignee
     *
     * @mbg.generated Thu Jun 28 18:05:45 CST 2018
     */
    private String consignee;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_order.mobile
     *
     * @mbg.generated Thu Jun 28 18:05:45 CST 2018
     */
    private String mobile;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_order.address
     *
     * @mbg.generated Thu Jun 28 18:05:45 CST 2018
     */
    private String address;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_order.goods_price
     *
     * @mbg.generated Thu Jun 28 18:05:45 CST 2018
     */
    private BigDecimal goodsPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_order.freight_price
     *
     * @mbg.generated Thu Jun 28 18:05:45 CST 2018
     */
    private BigDecimal freightPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_order.coupon_price
     *
     * @mbg.generated Thu Jun 28 18:05:45 CST 2018
     */
    private BigDecimal couponPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_order.integral_price
     *
     * @mbg.generated Thu Jun 28 18:05:45 CST 2018
     */
    private BigDecimal integralPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_order.order_price
     *
     * @mbg.generated Thu Jun 28 18:05:45 CST 2018
     */
    private BigDecimal orderPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_order.actual_price
     *
     * @mbg.generated Thu Jun 28 18:05:45 CST 2018
     */
    private BigDecimal actualPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_order.pay_id
     *
     * @mbg.generated Thu Jun 28 18:05:45 CST 2018
     */
    private String payId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_order.pay_status
     *
     * @mbg.generated Thu Jun 28 18:05:45 CST 2018
     */
    private Short payStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_order.pay_time
     *
     * @mbg.generated Thu Jun 28 18:05:45 CST 2018
     */
    private LocalDateTime payTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_order.ship_sn
     *
     * @mbg.generated Thu Jun 28 18:05:45 CST 2018
     */
    private String shipSn;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_order.ship_channel
     *
     * @mbg.generated Thu Jun 28 18:05:45 CST 2018
     */
    private String shipChannel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_order.ship_start_time
     *
     * @mbg.generated Thu Jun 28 18:05:45 CST 2018
     */
    private LocalDateTime shipStartTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_order.ship_end_time
     *
     * @mbg.generated Thu Jun 28 18:05:45 CST 2018
     */
    private LocalDateTime shipEndTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_order.confirm_time
     *
     * @mbg.generated Thu Jun 28 18:05:45 CST 2018
     */
    private LocalDateTime confirmTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_order.end_time
     *
     * @mbg.generated Thu Jun 28 18:05:45 CST 2018
     */
    private LocalDateTime endTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_order.add_time
     *
     * @mbg.generated Thu Jun 28 18:05:45 CST 2018
     */
    private LocalDateTime addTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_order.deleted
     *
     * @mbg.generated Thu Jun 28 18:05:45 CST 2018
     */
    private Boolean deleted;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_order.id
     *
     * @return the value of shop_order.id
     *
     * @mbg.generated Thu Jun 28 18:05:45 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_order.id
     *
     * @param id the value for shop_order.id
     *
     * @mbg.generated Thu Jun 28 18:05:45 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_order.user_id
     *
     * @return the value of shop_order.user_id
     *
     * @mbg.generated Thu Jun 28 18:05:45 CST 2018
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_order.user_id
     *
     * @param userId the value for shop_order.user_id
     *
     * @mbg.generated Thu Jun 28 18:05:45 CST 2018
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_order.order_sn
     *
     * @return the value of shop_order.order_sn
     *
     * @mbg.generated Thu Jun 28 18:05:45 CST 2018
     */
    public String getOrderSn() {
        return orderSn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_order.order_sn
     *
     * @param orderSn the value for shop_order.order_sn
     *
     * @mbg.generated Thu Jun 28 18:05:45 CST 2018
     */
    public void setOrderSn(String orderSn) {
        this.orderSn = orderSn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_order.order_status
     *
     * @return the value of shop_order.order_status
     *
     * @mbg.generated Thu Jun 28 18:05:45 CST 2018
     */
    public Short getOrderStatus() {
        return orderStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_order.order_status
     *
     * @param orderStatus the value for shop_order.order_status
     *
     * @mbg.generated Thu Jun 28 18:05:45 CST 2018
     */
    public void setOrderStatus(Short orderStatus) {
        this.orderStatus = orderStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_order.consignee
     *
     * @return the value of shop_order.consignee
     *
     * @mbg.generated Thu Jun 28 18:05:45 CST 2018
     */
    public String getConsignee() {
        return consignee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_order.consignee
     *
     * @param consignee the value for shop_order.consignee
     *
     * @mbg.generated Thu Jun 28 18:05:45 CST 2018
     */
    public void setConsignee(String consignee) {
        this.consignee = consignee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_order.mobile
     *
     * @return the value of shop_order.mobile
     *
     * @mbg.generated Thu Jun 28 18:05:45 CST 2018
     */
    public String getMobile() {
        return mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_order.mobile
     *
     * @param mobile the value for shop_order.mobile
     *
     * @mbg.generated Thu Jun 28 18:05:45 CST 2018
     */
    public void setMobile(String mobile) {
        this.mobile = mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_order.address
     *
     * @return the value of shop_order.address
     *
     * @mbg.generated Thu Jun 28 18:05:45 CST 2018
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_order.address
     *
     * @param address the value for shop_order.address
     *
     * @mbg.generated Thu Jun 28 18:05:45 CST 2018
     */
    public void setAddress(String address) {
        this.address = address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_order.goods_price
     *
     * @return the value of shop_order.goods_price
     *
     * @mbg.generated Thu Jun 28 18:05:45 CST 2018
     */
    public BigDecimal getGoodsPrice() {
        return goodsPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_order.goods_price
     *
     * @param goodsPrice the value for shop_order.goods_price
     *
     * @mbg.generated Thu Jun 28 18:05:45 CST 2018
     */
    public void setGoodsPrice(BigDecimal goodsPrice) {
        this.goodsPrice = goodsPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_order.freight_price
     *
     * @return the value of shop_order.freight_price
     *
     * @mbg.generated Thu Jun 28 18:05:45 CST 2018
     */
    public BigDecimal getFreightPrice() {
        return freightPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_order.freight_price
     *
     * @param freightPrice the value for shop_order.freight_price
     *
     * @mbg.generated Thu Jun 28 18:05:45 CST 2018
     */
    public void setFreightPrice(BigDecimal freightPrice) {
        this.freightPrice = freightPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_order.coupon_price
     *
     * @return the value of shop_order.coupon_price
     *
     * @mbg.generated Thu Jun 28 18:05:45 CST 2018
     */
    public BigDecimal getCouponPrice() {
        return couponPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_order.coupon_price
     *
     * @param couponPrice the value for shop_order.coupon_price
     *
     * @mbg.generated Thu Jun 28 18:05:45 CST 2018
     */
    public void setCouponPrice(BigDecimal couponPrice) {
        this.couponPrice = couponPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_order.integral_price
     *
     * @return the value of shop_order.integral_price
     *
     * @mbg.generated Thu Jun 28 18:05:45 CST 2018
     */
    public BigDecimal getIntegralPrice() {
        return integralPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_order.integral_price
     *
     * @param integralPrice the value for shop_order.integral_price
     *
     * @mbg.generated Thu Jun 28 18:05:45 CST 2018
     */
    public void setIntegralPrice(BigDecimal integralPrice) {
        this.integralPrice = integralPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_order.order_price
     *
     * @return the value of shop_order.order_price
     *
     * @mbg.generated Thu Jun 28 18:05:45 CST 2018
     */
    public BigDecimal getOrderPrice() {
        return orderPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_order.order_price
     *
     * @param orderPrice the value for shop_order.order_price
     *
     * @mbg.generated Thu Jun 28 18:05:45 CST 2018
     */
    public void setOrderPrice(BigDecimal orderPrice) {
        this.orderPrice = orderPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_order.actual_price
     *
     * @return the value of shop_order.actual_price
     *
     * @mbg.generated Thu Jun 28 18:05:45 CST 2018
     */
    public BigDecimal getActualPrice() {
        return actualPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_order.actual_price
     *
     * @param actualPrice the value for shop_order.actual_price
     *
     * @mbg.generated Thu Jun 28 18:05:45 CST 2018
     */
    public void setActualPrice(BigDecimal actualPrice) {
        this.actualPrice = actualPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_order.pay_id
     *
     * @return the value of shop_order.pay_id
     *
     * @mbg.generated Thu Jun 28 18:05:45 CST 2018
     */
    public String getPayId() {
        return payId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_order.pay_id
     *
     * @param payId the value for shop_order.pay_id
     *
     * @mbg.generated Thu Jun 28 18:05:45 CST 2018
     */
    public void setPayId(String payId) {
        this.payId = payId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_order.pay_status
     *
     * @return the value of shop_order.pay_status
     *
     * @mbg.generated Thu Jun 28 18:05:45 CST 2018
     */
    public Short getPayStatus() {
        return payStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_order.pay_status
     *
     * @param payStatus the value for shop_order.pay_status
     *
     * @mbg.generated Thu Jun 28 18:05:45 CST 2018
     */
    public void setPayStatus(Short payStatus) {
        this.payStatus = payStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_order.pay_time
     *
     * @return the value of shop_order.pay_time
     *
     * @mbg.generated Thu Jun 28 18:05:45 CST 2018
     */
    public LocalDateTime getPayTime() {
        return payTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_order.pay_time
     *
     * @param payTime the value for shop_order.pay_time
     *
     * @mbg.generated Thu Jun 28 18:05:45 CST 2018
     */
    public void setPayTime(LocalDateTime payTime) {
        this.payTime = payTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_order.ship_sn
     *
     * @return the value of shop_order.ship_sn
     *
     * @mbg.generated Thu Jun 28 18:05:45 CST 2018
     */
    public String getShipSn() {
        return shipSn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_order.ship_sn
     *
     * @param shipSn the value for shop_order.ship_sn
     *
     * @mbg.generated Thu Jun 28 18:05:45 CST 2018
     */
    public void setShipSn(String shipSn) {
        this.shipSn = shipSn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_order.ship_channel
     *
     * @return the value of shop_order.ship_channel
     *
     * @mbg.generated Thu Jun 28 18:05:45 CST 2018
     */
    public String getShipChannel() {
        return shipChannel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_order.ship_channel
     *
     * @param shipChannel the value for shop_order.ship_channel
     *
     * @mbg.generated Thu Jun 28 18:05:45 CST 2018
     */
    public void setShipChannel(String shipChannel) {
        this.shipChannel = shipChannel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_order.ship_start_time
     *
     * @return the value of shop_order.ship_start_time
     *
     * @mbg.generated Thu Jun 28 18:05:45 CST 2018
     */
    public LocalDateTime getShipStartTime() {
        return shipStartTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_order.ship_start_time
     *
     * @param shipStartTime the value for shop_order.ship_start_time
     *
     * @mbg.generated Thu Jun 28 18:05:45 CST 2018
     */
    public void setShipStartTime(LocalDateTime shipStartTime) {
        this.shipStartTime = shipStartTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_order.ship_end_time
     *
     * @return the value of shop_order.ship_end_time
     *
     * @mbg.generated Thu Jun 28 18:05:45 CST 2018
     */
    public LocalDateTime getShipEndTime() {
        return shipEndTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_order.ship_end_time
     *
     * @param shipEndTime the value for shop_order.ship_end_time
     *
     * @mbg.generated Thu Jun 28 18:05:45 CST 2018
     */
    public void setShipEndTime(LocalDateTime shipEndTime) {
        this.shipEndTime = shipEndTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_order.confirm_time
     *
     * @return the value of shop_order.confirm_time
     *
     * @mbg.generated Thu Jun 28 18:05:45 CST 2018
     */
    public LocalDateTime getConfirmTime() {
        return confirmTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_order.confirm_time
     *
     * @param confirmTime the value for shop_order.confirm_time
     *
     * @mbg.generated Thu Jun 28 18:05:45 CST 2018
     */
    public void setConfirmTime(LocalDateTime confirmTime) {
        this.confirmTime = confirmTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_order.end_time
     *
     * @return the value of shop_order.end_time
     *
     * @mbg.generated Thu Jun 28 18:05:45 CST 2018
     */
    public LocalDateTime getEndTime() {
        return endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_order.end_time
     *
     * @param endTime the value for shop_order.end_time
     *
     * @mbg.generated Thu Jun 28 18:05:45 CST 2018
     */
    public void setEndTime(LocalDateTime endTime) {
        this.endTime = endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_order.add_time
     *
     * @return the value of shop_order.add_time
     *
     * @mbg.generated Thu Jun 28 18:05:45 CST 2018
     */
    public LocalDateTime getAddTime() {
        return addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_order.add_time
     *
     * @param addTime the value for shop_order.add_time
     *
     * @mbg.generated Thu Jun 28 18:05:45 CST 2018
     */
    public void setAddTime(LocalDateTime addTime) {
        this.addTime = addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_order.deleted
     *
     * @return the value of shop_order.deleted
     *
     * @mbg.generated Thu Jun 28 18:05:45 CST 2018
     */
    public Boolean getDeleted() {
        return deleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_order.deleted
     *
     * @param deleted the value for shop_order.deleted
     *
     * @mbg.generated Thu Jun 28 18:05:45 CST 2018
     */
    public void setDeleted(Boolean deleted) {
        this.deleted = deleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_order
     *
     * @mbg.generated Thu Jun 28 18:05:45 CST 2018
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", userId=").append(userId);
        sb.append(", orderSn=").append(orderSn);
        sb.append(", orderStatus=").append(orderStatus);
        sb.append(", consignee=").append(consignee);
        sb.append(", mobile=").append(mobile);
        sb.append(", address=").append(address);
        sb.append(", goodsPrice=").append(goodsPrice);
        sb.append(", freightPrice=").append(freightPrice);
        sb.append(", couponPrice=").append(couponPrice);
        sb.append(", integralPrice=").append(integralPrice);
        sb.append(", orderPrice=").append(orderPrice);
        sb.append(", actualPrice=").append(actualPrice);
        sb.append(", payId=").append(payId);
        sb.append(", payStatus=").append(payStatus);
        sb.append(", payTime=").append(payTime);
        sb.append(", shipSn=").append(shipSn);
        sb.append(", shipChannel=").append(shipChannel);
        sb.append(", shipStartTime=").append(shipStartTime);
        sb.append(", shipEndTime=").append(shipEndTime);
        sb.append(", confirmTime=").append(confirmTime);
        sb.append(", endTime=").append(endTime);
        sb.append(", addTime=").append(addTime);
        sb.append(", deleted=").append(deleted);
        sb.append("]");
        return sb.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_order
     *
     * @mbg.generated Thu Jun 28 18:05:45 CST 2018
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        ShopOrder other = (ShopOrder) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getUserId() == null ? other.getUserId() == null : this.getUserId().equals(other.getUserId()))
            && (this.getOrderSn() == null ? other.getOrderSn() == null : this.getOrderSn().equals(other.getOrderSn()))
            && (this.getOrderStatus() == null ? other.getOrderStatus() == null : this.getOrderStatus().equals(other.getOrderStatus()))
            && (this.getConsignee() == null ? other.getConsignee() == null : this.getConsignee().equals(other.getConsignee()))
            && (this.getMobile() == null ? other.getMobile() == null : this.getMobile().equals(other.getMobile()))
            && (this.getAddress() == null ? other.getAddress() == null : this.getAddress().equals(other.getAddress()))
            && (this.getGoodsPrice() == null ? other.getGoodsPrice() == null : this.getGoodsPrice().equals(other.getGoodsPrice()))
            && (this.getFreightPrice() == null ? other.getFreightPrice() == null : this.getFreightPrice().equals(other.getFreightPrice()))
            && (this.getCouponPrice() == null ? other.getCouponPrice() == null : this.getCouponPrice().equals(other.getCouponPrice()))
            && (this.getIntegralPrice() == null ? other.getIntegralPrice() == null : this.getIntegralPrice().equals(other.getIntegralPrice()))
            && (this.getOrderPrice() == null ? other.getOrderPrice() == null : this.getOrderPrice().equals(other.getOrderPrice()))
            && (this.getActualPrice() == null ? other.getActualPrice() == null : this.getActualPrice().equals(other.getActualPrice()))
            && (this.getPayId() == null ? other.getPayId() == null : this.getPayId().equals(other.getPayId()))
            && (this.getPayStatus() == null ? other.getPayStatus() == null : this.getPayStatus().equals(other.getPayStatus()))
            && (this.getPayTime() == null ? other.getPayTime() == null : this.getPayTime().equals(other.getPayTime()))
            && (this.getShipSn() == null ? other.getShipSn() == null : this.getShipSn().equals(other.getShipSn()))
            && (this.getShipChannel() == null ? other.getShipChannel() == null : this.getShipChannel().equals(other.getShipChannel()))
            && (this.getShipStartTime() == null ? other.getShipStartTime() == null : this.getShipStartTime().equals(other.getShipStartTime()))
            && (this.getShipEndTime() == null ? other.getShipEndTime() == null : this.getShipEndTime().equals(other.getShipEndTime()))
            && (this.getConfirmTime() == null ? other.getConfirmTime() == null : this.getConfirmTime().equals(other.getConfirmTime()))
            && (this.getEndTime() == null ? other.getEndTime() == null : this.getEndTime().equals(other.getEndTime()))
            && (this.getAddTime() == null ? other.getAddTime() == null : this.getAddTime().equals(other.getAddTime()))
            && (this.getDeleted() == null ? other.getDeleted() == null : this.getDeleted().equals(other.getDeleted()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_order
     *
     * @mbg.generated Thu Jun 28 18:05:45 CST 2018
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getUserId() == null) ? 0 : getUserId().hashCode());
        result = prime * result + ((getOrderSn() == null) ? 0 : getOrderSn().hashCode());
        result = prime * result + ((getOrderStatus() == null) ? 0 : getOrderStatus().hashCode());
        result = prime * result + ((getConsignee() == null) ? 0 : getConsignee().hashCode());
        result = prime * result + ((getMobile() == null) ? 0 : getMobile().hashCode());
        result = prime * result + ((getAddress() == null) ? 0 : getAddress().hashCode());
        result = prime * result + ((getGoodsPrice() == null) ? 0 : getGoodsPrice().hashCode());
        result = prime * result + ((getFreightPrice() == null) ? 0 : getFreightPrice().hashCode());
        result = prime * result + ((getCouponPrice() == null) ? 0 : getCouponPrice().hashCode());
        result = prime * result + ((getIntegralPrice() == null) ? 0 : getIntegralPrice().hashCode());
        result = prime * result + ((getOrderPrice() == null) ? 0 : getOrderPrice().hashCode());
        result = prime * result + ((getActualPrice() == null) ? 0 : getActualPrice().hashCode());
        result = prime * result + ((getPayId() == null) ? 0 : getPayId().hashCode());
        result = prime * result + ((getPayStatus() == null) ? 0 : getPayStatus().hashCode());
        result = prime * result + ((getPayTime() == null) ? 0 : getPayTime().hashCode());
        result = prime * result + ((getShipSn() == null) ? 0 : getShipSn().hashCode());
        result = prime * result + ((getShipChannel() == null) ? 0 : getShipChannel().hashCode());
        result = prime * result + ((getShipStartTime() == null) ? 0 : getShipStartTime().hashCode());
        result = prime * result + ((getShipEndTime() == null) ? 0 : getShipEndTime().hashCode());
        result = prime * result + ((getConfirmTime() == null) ? 0 : getConfirmTime().hashCode());
        result = prime * result + ((getEndTime() == null) ? 0 : getEndTime().hashCode());
        result = prime * result + ((getAddTime() == null) ? 0 : getAddTime().hashCode());
        result = prime * result + ((getDeleted() == null) ? 0 : getDeleted().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_order
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    public void andLogicalDeleted(boolean deleted) {
        setDeleted(deleted ? IS_DELETED : NOT_DELETED);
    }

    /**
     * This enum was generated by MyBatis Generator.
     * This enum corresponds to the database table shop_order
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    public enum Column {
        id("id", "id", "INTEGER"),
        userId("user_id", "userId", "INTEGER"),
        orderSn("order_sn", "orderSn", "VARCHAR"),
        orderStatus("order_status", "orderStatus", "SMALLINT"),
        consignee("consignee", "consignee", "VARCHAR"),
        mobile("mobile", "mobile", "VARCHAR"),
        address("address", "address", "VARCHAR"),
        goodsPrice("goods_price", "goodsPrice", "DECIMAL"),
        freightPrice("freight_price", "freightPrice", "DECIMAL"),
        couponPrice("coupon_price", "couponPrice", "DECIMAL"),
        integralPrice("integral_price", "integralPrice", "DECIMAL"),
        orderPrice("order_price", "orderPrice", "DECIMAL"),
        actualPrice("actual_price", "actualPrice", "DECIMAL"),
        payId("pay_id", "payId", "VARCHAR"),
        payStatus("pay_status", "payStatus", "SMALLINT"),
        payTime("pay_time", "payTime", "TIMESTAMP"),
        shipSn("ship_sn", "shipSn", "VARCHAR"),
        shipChannel("ship_channel", "shipChannel", "VARCHAR"),
        shipStartTime("ship_start_time", "shipStartTime", "TIMESTAMP"),
        shipEndTime("ship_end_time", "shipEndTime", "TIMESTAMP"),
        confirmTime("confirm_time", "confirmTime", "TIMESTAMP"),
        endTime("end_time", "endTime", "TIMESTAMP"),
        addTime("add_time", "addTime", "TIMESTAMP"),
        deleted("deleted", "deleted", "BIT");

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table shop_order
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        private final String column;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table shop_order
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        private final String javaProperty;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table shop_order
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        private final String jdbcType;

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table shop_order
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String value() {
            return this.column;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table shop_order
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String getValue() {
            return this.column;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table shop_order
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String getJavaProperty() {
            return this.javaProperty;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table shop_order
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String getJdbcType() {
            return this.jdbcType;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table shop_order
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        Column(String column, String javaProperty, String jdbcType) {
            this.column = column;
            this.javaProperty = javaProperty;
            this.jdbcType = jdbcType;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table shop_order
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String desc() {
            return this.column + " DESC";
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table shop_order
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String asc() {
            return this.column + " ASC";
        }
    }
}