package manman.pro.db.domain;

import java.math.BigDecimal;
import java.time.LocalDateTime;
import java.util.Arrays;

public class ShopCart {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table shop_cart
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    public static final Boolean NOT_DELETED = false;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table shop_cart
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    @Deprecated
    public static final Boolean DEL_FLAG_ON = false;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table shop_cart
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    public static final Boolean IS_DELETED = true;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table shop_cart
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    @Deprecated
    public static final Boolean DEL_FLAG_OFF = true;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_cart.id
     *
     * @mbg.generated Thu Jun 28 18:05:45 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_cart.user_id
     *
     * @mbg.generated Thu Jun 28 18:05:45 CST 2018
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_cart.goods_id
     *
     * @mbg.generated Thu Jun 28 18:05:45 CST 2018
     */
    private Integer goodsId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_cart.goods_sn
     *
     * @mbg.generated Thu Jun 28 18:05:45 CST 2018
     */
    private String goodsSn;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_cart.product_id
     *
     * @mbg.generated Thu Jun 28 18:05:45 CST 2018
     */
    private Integer productId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_cart.goods_name
     *
     * @mbg.generated Thu Jun 28 18:05:45 CST 2018
     */
    private String goodsName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_cart.retail_price
     *
     * @mbg.generated Thu Jun 28 18:05:45 CST 2018
     */
    private BigDecimal retailPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_cart.number
     *
     * @mbg.generated Thu Jun 28 18:05:45 CST 2018
     */
    private Short number;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_cart.goods_specification_values
     *
     * @mbg.generated Thu Jun 28 18:05:45 CST 2018
     */
    private String goodsSpecificationValues;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_cart.goods_specification_ids
     *
     * @mbg.generated Thu Jun 28 18:05:45 CST 2018
     */
    private Integer[] goodsSpecificationIds;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_cart.checked
     *
     * @mbg.generated Thu Jun 28 18:05:45 CST 2018
     */
    private Boolean checked;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_cart.pic_url
     *
     * @mbg.generated Thu Jun 28 18:05:45 CST 2018
     */
    private String picUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_cart.add_time
     *
     * @mbg.generated Thu Jun 28 18:05:45 CST 2018
     */
    private LocalDateTime addTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_cart.deleted
     *
     * @mbg.generated Thu Jun 28 18:05:45 CST 2018
     */
    private Boolean deleted;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_cart.id
     *
     * @return the value of shop_cart.id
     *
     * @mbg.generated Thu Jun 28 18:05:45 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_cart.id
     *
     * @param id the value for shop_cart.id
     *
     * @mbg.generated Thu Jun 28 18:05:45 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_cart.user_id
     *
     * @return the value of shop_cart.user_id
     *
     * @mbg.generated Thu Jun 28 18:05:45 CST 2018
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_cart.user_id
     *
     * @param userId the value for shop_cart.user_id
     *
     * @mbg.generated Thu Jun 28 18:05:45 CST 2018
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_cart.goods_id
     *
     * @return the value of shop_cart.goods_id
     *
     * @mbg.generated Thu Jun 28 18:05:45 CST 2018
     */
    public Integer getGoodsId() {
        return goodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_cart.goods_id
     *
     * @param goodsId the value for shop_cart.goods_id
     *
     * @mbg.generated Thu Jun 28 18:05:45 CST 2018
     */
    public void setGoodsId(Integer goodsId) {
        this.goodsId = goodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_cart.goods_sn
     *
     * @return the value of shop_cart.goods_sn
     *
     * @mbg.generated Thu Jun 28 18:05:45 CST 2018
     */
    public String getGoodsSn() {
        return goodsSn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_cart.goods_sn
     *
     * @param goodsSn the value for shop_cart.goods_sn
     *
     * @mbg.generated Thu Jun 28 18:05:45 CST 2018
     */
    public void setGoodsSn(String goodsSn) {
        this.goodsSn = goodsSn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_cart.product_id
     *
     * @return the value of shop_cart.product_id
     *
     * @mbg.generated Thu Jun 28 18:05:45 CST 2018
     */
    public Integer getProductId() {
        return productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_cart.product_id
     *
     * @param productId the value for shop_cart.product_id
     *
     * @mbg.generated Thu Jun 28 18:05:45 CST 2018
     */
    public void setProductId(Integer productId) {
        this.productId = productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_cart.goods_name
     *
     * @return the value of shop_cart.goods_name
     *
     * @mbg.generated Thu Jun 28 18:05:45 CST 2018
     */
    public String getGoodsName() {
        return goodsName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_cart.goods_name
     *
     * @param goodsName the value for shop_cart.goods_name
     *
     * @mbg.generated Thu Jun 28 18:05:45 CST 2018
     */
    public void setGoodsName(String goodsName) {
        this.goodsName = goodsName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_cart.retail_price
     *
     * @return the value of shop_cart.retail_price
     *
     * @mbg.generated Thu Jun 28 18:05:45 CST 2018
     */
    public BigDecimal getRetailPrice() {
        return retailPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_cart.retail_price
     *
     * @param retailPrice the value for shop_cart.retail_price
     *
     * @mbg.generated Thu Jun 28 18:05:45 CST 2018
     */
    public void setRetailPrice(BigDecimal retailPrice) {
        this.retailPrice = retailPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_cart.number
     *
     * @return the value of shop_cart.number
     *
     * @mbg.generated Thu Jun 28 18:05:45 CST 2018
     */
    public Short getNumber() {
        return number;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_cart.number
     *
     * @param number the value for shop_cart.number
     *
     * @mbg.generated Thu Jun 28 18:05:45 CST 2018
     */
    public void setNumber(Short number) {
        this.number = number;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_cart.goods_specification_values
     *
     * @return the value of shop_cart.goods_specification_values
     *
     * @mbg.generated Thu Jun 28 18:05:45 CST 2018
     */
    public String getGoodsSpecificationValues() {
        return goodsSpecificationValues;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_cart.goods_specification_values
     *
     * @param goodsSpecificationValues the value for shop_cart.goods_specification_values
     *
     * @mbg.generated Thu Jun 28 18:05:45 CST 2018
     */
    public void setGoodsSpecificationValues(String goodsSpecificationValues) {
        this.goodsSpecificationValues = goodsSpecificationValues;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_cart.goods_specification_ids
     *
     * @return the value of shop_cart.goods_specification_ids
     *
     * @mbg.generated Thu Jun 28 18:05:45 CST 2018
     */
    public Integer[] getGoodsSpecificationIds() {
        return goodsSpecificationIds;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_cart.goods_specification_ids
     *
     * @param goodsSpecificationIds the value for shop_cart.goods_specification_ids
     *
     * @mbg.generated Thu Jun 28 18:05:45 CST 2018
     */
    public void setGoodsSpecificationIds(Integer[] goodsSpecificationIds) {
        this.goodsSpecificationIds = goodsSpecificationIds;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_cart.checked
     *
     * @return the value of shop_cart.checked
     *
     * @mbg.generated Thu Jun 28 18:05:45 CST 2018
     */
    public Boolean getChecked() {
        return checked;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_cart.checked
     *
     * @param checked the value for shop_cart.checked
     *
     * @mbg.generated Thu Jun 28 18:05:45 CST 2018
     */
    public void setChecked(Boolean checked) {
        this.checked = checked;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_cart.pic_url
     *
     * @return the value of shop_cart.pic_url
     *
     * @mbg.generated Thu Jun 28 18:05:45 CST 2018
     */
    public String getPicUrl() {
        return picUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_cart.pic_url
     *
     * @param picUrl the value for shop_cart.pic_url
     *
     * @mbg.generated Thu Jun 28 18:05:45 CST 2018
     */
    public void setPicUrl(String picUrl) {
        this.picUrl = picUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_cart.add_time
     *
     * @return the value of shop_cart.add_time
     *
     * @mbg.generated Thu Jun 28 18:05:45 CST 2018
     */
    public LocalDateTime getAddTime() {
        return addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_cart.add_time
     *
     * @param addTime the value for shop_cart.add_time
     *
     * @mbg.generated Thu Jun 28 18:05:45 CST 2018
     */
    public void setAddTime(LocalDateTime addTime) {
        this.addTime = addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_cart.deleted
     *
     * @return the value of shop_cart.deleted
     *
     * @mbg.generated Thu Jun 28 18:05:45 CST 2018
     */
    public Boolean getDeleted() {
        return deleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_cart.deleted
     *
     * @param deleted the value for shop_cart.deleted
     *
     * @mbg.generated Thu Jun 28 18:05:45 CST 2018
     */
    public void setDeleted(Boolean deleted) {
        this.deleted = deleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_cart
     *
     * @mbg.generated Thu Jun 28 18:05:45 CST 2018
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", userId=").append(userId);
        sb.append(", goodsId=").append(goodsId);
        sb.append(", goodsSn=").append(goodsSn);
        sb.append(", productId=").append(productId);
        sb.append(", goodsName=").append(goodsName);
        sb.append(", retailPrice=").append(retailPrice);
        sb.append(", number=").append(number);
        sb.append(", goodsSpecificationValues=").append(goodsSpecificationValues);
        sb.append(", goodsSpecificationIds=").append(goodsSpecificationIds);
        sb.append(", checked=").append(checked);
        sb.append(", picUrl=").append(picUrl);
        sb.append(", addTime=").append(addTime);
        sb.append(", deleted=").append(deleted);
        sb.append("]");
        return sb.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_cart
     *
     * @mbg.generated Thu Jun 28 18:05:45 CST 2018
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        ShopCart other = (ShopCart) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getUserId() == null ? other.getUserId() == null : this.getUserId().equals(other.getUserId()))
            && (this.getGoodsId() == null ? other.getGoodsId() == null : this.getGoodsId().equals(other.getGoodsId()))
            && (this.getGoodsSn() == null ? other.getGoodsSn() == null : this.getGoodsSn().equals(other.getGoodsSn()))
            && (this.getProductId() == null ? other.getProductId() == null : this.getProductId().equals(other.getProductId()))
            && (this.getGoodsName() == null ? other.getGoodsName() == null : this.getGoodsName().equals(other.getGoodsName()))
            && (this.getRetailPrice() == null ? other.getRetailPrice() == null : this.getRetailPrice().equals(other.getRetailPrice()))
            && (this.getNumber() == null ? other.getNumber() == null : this.getNumber().equals(other.getNumber()))
            && (this.getGoodsSpecificationValues() == null ? other.getGoodsSpecificationValues() == null : this.getGoodsSpecificationValues().equals(other.getGoodsSpecificationValues()))
            && (Arrays.equals(this.getGoodsSpecificationIds(), other.getGoodsSpecificationIds()))
            && (this.getChecked() == null ? other.getChecked() == null : this.getChecked().equals(other.getChecked()))
            && (this.getPicUrl() == null ? other.getPicUrl() == null : this.getPicUrl().equals(other.getPicUrl()))
            && (this.getAddTime() == null ? other.getAddTime() == null : this.getAddTime().equals(other.getAddTime()))
            && (this.getDeleted() == null ? other.getDeleted() == null : this.getDeleted().equals(other.getDeleted()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_cart
     *
     * @mbg.generated Thu Jun 28 18:05:45 CST 2018
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getUserId() == null) ? 0 : getUserId().hashCode());
        result = prime * result + ((getGoodsId() == null) ? 0 : getGoodsId().hashCode());
        result = prime * result + ((getGoodsSn() == null) ? 0 : getGoodsSn().hashCode());
        result = prime * result + ((getProductId() == null) ? 0 : getProductId().hashCode());
        result = prime * result + ((getGoodsName() == null) ? 0 : getGoodsName().hashCode());
        result = prime * result + ((getRetailPrice() == null) ? 0 : getRetailPrice().hashCode());
        result = prime * result + ((getNumber() == null) ? 0 : getNumber().hashCode());
        result = prime * result + ((getGoodsSpecificationValues() == null) ? 0 : getGoodsSpecificationValues().hashCode());
        result = prime * result + (Arrays.hashCode(getGoodsSpecificationIds()));
        result = prime * result + ((getChecked() == null) ? 0 : getChecked().hashCode());
        result = prime * result + ((getPicUrl() == null) ? 0 : getPicUrl().hashCode());
        result = prime * result + ((getAddTime() == null) ? 0 : getAddTime().hashCode());
        result = prime * result + ((getDeleted() == null) ? 0 : getDeleted().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_cart
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    public void andLogicalDeleted(boolean deleted) {
        setDeleted(deleted ? IS_DELETED : NOT_DELETED);
    }

    /**
     * This enum was generated by MyBatis Generator.
     * This enum corresponds to the database table shop_cart
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    public enum Column {
        id("id", "id", "INTEGER"),
        userId("user_id", "userId", "INTEGER"),
        goodsId("goods_id", "goodsId", "INTEGER"),
        goodsSn("goods_sn", "goodsSn", "VARCHAR"),
        productId("product_id", "productId", "INTEGER"),
        goodsName("goods_name", "goodsName", "VARCHAR"),
        retailPrice("retail_price", "retailPrice", "DECIMAL"),
        number("number", "number", "SMALLINT"),
        goodsSpecificationValues("goods_specification_values", "goodsSpecificationValues", "VARCHAR"),
        goodsSpecificationIds("goods_specification_ids", "goodsSpecificationIds", "CHAR"),
        checked("checked", "checked", "BIT"),
        picUrl("pic_url", "picUrl", "VARCHAR"),
        addTime("add_time", "addTime", "TIMESTAMP"),
        deleted("deleted", "deleted", "BIT");

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table shop_cart
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        private final String column;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table shop_cart
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        private final String javaProperty;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table shop_cart
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        private final String jdbcType;

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table shop_cart
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String value() {
            return this.column;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table shop_cart
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String getValue() {
            return this.column;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table shop_cart
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String getJavaProperty() {
            return this.javaProperty;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table shop_cart
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String getJdbcType() {
            return this.jdbcType;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table shop_cart
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        Column(String column, String javaProperty, String jdbcType) {
            this.column = column;
            this.javaProperty = javaProperty;
            this.jdbcType = jdbcType;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table shop_cart
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String desc() {
            return this.column + " DESC";
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table shop_cart
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String asc() {
            return this.column + " ASC";
        }
    }
}