package manman.pro.db.dao;

import java.util.List;
import manman.pro.db.domain.ShopFootprint;
import manman.pro.db.domain.ShopFootprintExample;
import org.apache.ibatis.annotations.Param;

public interface ShopFootprintMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_footprint
     *
     * @mbg.generated Thu Jun 28 18:05:45 CST 2018
     */
    long countByExample(ShopFootprintExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_footprint
     *
     * @mbg.generated Thu Jun 28 18:05:45 CST 2018
     */
    int deleteByExample(ShopFootprintExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_footprint
     *
     * @mbg.generated Thu Jun 28 18:05:45 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_footprint
     *
     * @mbg.generated Thu Jun 28 18:05:45 CST 2018
     */
    int insert(ShopFootprint record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_footprint
     *
     * @mbg.generated Thu Jun 28 18:05:45 CST 2018
     */
    int insertSelective(ShopFootprint record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_footprint
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    ShopFootprint selectOneByExample(ShopFootprintExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_footprint
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    ShopFootprint selectOneByExampleSelective(@Param("example") ShopFootprintExample example, @Param("selective") ShopFootprint.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_footprint
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    List<ShopFootprint> selectByExampleSelective(@Param("example") ShopFootprintExample example, @Param("selective") ShopFootprint.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_footprint
     *
     * @mbg.generated Thu Jun 28 18:05:45 CST 2018
     */
    List<ShopFootprint> selectByExample(ShopFootprintExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_footprint
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    ShopFootprint selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") ShopFootprint.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_footprint
     *
     * @mbg.generated Thu Jun 28 18:05:45 CST 2018
     */
    ShopFootprint selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_footprint
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    ShopFootprint selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_footprint
     *
     * @mbg.generated Thu Jun 28 18:05:45 CST 2018
     */
    int updateByExampleSelective(@Param("record") ShopFootprint record, @Param("example") ShopFootprintExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_footprint
     *
     * @mbg.generated Thu Jun 28 18:05:45 CST 2018
     */
    int updateByExample(@Param("record") ShopFootprint record, @Param("example") ShopFootprintExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_footprint
     *
     * @mbg.generated Thu Jun 28 18:05:45 CST 2018
     */
    int updateByPrimaryKeySelective(ShopFootprint record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_footprint
     *
     * @mbg.generated Thu Jun 28 18:05:45 CST 2018
     */
    int updateByPrimaryKey(ShopFootprint record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_footprint
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByExample(@Param("example") ShopFootprintExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_footprint
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByPrimaryKey(Integer id);
}