package manman.pro.db.dao;

import java.util.List;
import manman.pro.db.domain.ShopAdmin;
import manman.pro.db.domain.ShopAdminExample;
import org.apache.ibatis.annotations.Param;

public interface ShopAdminMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_admin
     *
     * @mbg.generated Thu Jun 28 18:05:45 CST 2018
     */
    long countByExample(ShopAdminExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_admin
     *
     * @mbg.generated Thu Jun 28 18:05:45 CST 2018
     */
    int deleteByExample(ShopAdminExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_admin
     *
     * @mbg.generated Thu Jun 28 18:05:45 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_admin
     *
     * @mbg.generated Thu Jun 28 18:05:45 CST 2018
     */
    int insert(ShopAdmin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_admin
     *
     * @mbg.generated Thu Jun 28 18:05:45 CST 2018
     */
    int insertSelective(ShopAdmin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_admin
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    ShopAdmin selectOneByExample(ShopAdminExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_admin
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    ShopAdmin selectOneByExampleSelective(@Param("example") ShopAdminExample example, @Param("selective") ShopAdmin.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_admin
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    List<ShopAdmin> selectByExampleSelective(@Param("example") ShopAdminExample example, @Param("selective") ShopAdmin.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_admin
     *
     * @mbg.generated Thu Jun 28 18:05:45 CST 2018
     */
    List<ShopAdmin> selectByExample(ShopAdminExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_admin
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    ShopAdmin selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") ShopAdmin.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_admin
     *
     * @mbg.generated Thu Jun 28 18:05:45 CST 2018
     */
    ShopAdmin selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_admin
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    ShopAdmin selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_admin
     *
     * @mbg.generated Thu Jun 28 18:05:45 CST 2018
     */
    int updateByExampleSelective(@Param("record") ShopAdmin record, @Param("example") ShopAdminExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_admin
     *
     * @mbg.generated Thu Jun 28 18:05:45 CST 2018
     */
    int updateByExample(@Param("record") ShopAdmin record, @Param("example") ShopAdminExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_admin
     *
     * @mbg.generated Thu Jun 28 18:05:45 CST 2018
     */
    int updateByPrimaryKeySelective(ShopAdmin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_admin
     *
     * @mbg.generated Thu Jun 28 18:05:45 CST 2018
     */
    int updateByPrimaryKey(ShopAdmin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_admin
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByExample(@Param("example") ShopAdminExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_admin
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByPrimaryKey(Integer id);
}