package manman.pro.db.dao;

import java.util.List;
import manman.pro.db.domain.ShopCoupon;
import manman.pro.db.domain.ShopCouponExample;
import org.apache.ibatis.annotations.Param;

public interface ShopCouponMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_coupon
     *
     * @mbg.generated Thu Jun 28 18:05:45 CST 2018
     */
    long countByExample(ShopCouponExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_coupon
     *
     * @mbg.generated Thu Jun 28 18:05:45 CST 2018
     */
    int deleteByExample(ShopCouponExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_coupon
     *
     * @mbg.generated Thu Jun 28 18:05:45 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_coupon
     *
     * @mbg.generated Thu Jun 28 18:05:45 CST 2018
     */
    int insert(ShopCoupon record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_coupon
     *
     * @mbg.generated Thu Jun 28 18:05:45 CST 2018
     */
    int insertSelective(ShopCoupon record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_coupon
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    ShopCoupon selectOneByExample(ShopCouponExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_coupon
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    ShopCoupon selectOneByExampleSelective(@Param("example") ShopCouponExample example, @Param("selective") ShopCoupon.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_coupon
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    List<ShopCoupon> selectByExampleSelective(@Param("example") ShopCouponExample example, @Param("selective") ShopCoupon.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_coupon
     *
     * @mbg.generated Thu Jun 28 18:05:45 CST 2018
     */
    List<ShopCoupon> selectByExample(ShopCouponExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_coupon
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    ShopCoupon selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") ShopCoupon.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_coupon
     *
     * @mbg.generated Thu Jun 28 18:05:45 CST 2018
     */
    ShopCoupon selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_coupon
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    ShopCoupon selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_coupon
     *
     * @mbg.generated Thu Jun 28 18:05:45 CST 2018
     */
    int updateByExampleSelective(@Param("record") ShopCoupon record, @Param("example") ShopCouponExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_coupon
     *
     * @mbg.generated Thu Jun 28 18:05:45 CST 2018
     */
    int updateByExample(@Param("record") ShopCoupon record, @Param("example") ShopCouponExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_coupon
     *
     * @mbg.generated Thu Jun 28 18:05:45 CST 2018
     */
    int updateByPrimaryKeySelective(ShopCoupon record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_coupon
     *
     * @mbg.generated Thu Jun 28 18:05:45 CST 2018
     */
    int updateByPrimaryKey(ShopCoupon record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_coupon
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByExample(@Param("example") ShopCouponExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_coupon
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByPrimaryKey(Integer id);
}