package manman.pro.db.dao;

import java.util.List;
import manman.pro.db.domain.ShopStorage;
import manman.pro.db.domain.ShopStorageExample;
import org.apache.ibatis.annotations.Param;

public interface ShopStorageMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_storage
     *
     * @mbg.generated Thu Jun 28 18:05:45 CST 2018
     */
    long countByExample(ShopStorageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_storage
     *
     * @mbg.generated Thu Jun 28 18:05:45 CST 2018
     */
    int deleteByExample(ShopStorageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_storage
     *
     * @mbg.generated Thu Jun 28 18:05:45 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_storage
     *
     * @mbg.generated Thu Jun 28 18:05:45 CST 2018
     */
    int insert(ShopStorage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_storage
     *
     * @mbg.generated Thu Jun 28 18:05:45 CST 2018
     */
    int insertSelective(ShopStorage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_storage
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    ShopStorage selectOneByExample(ShopStorageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_storage
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    ShopStorage selectOneByExampleSelective(@Param("example") ShopStorageExample example, @Param("selective") ShopStorage.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_storage
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    List<ShopStorage> selectByExampleSelective(@Param("example") ShopStorageExample example, @Param("selective") ShopStorage.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_storage
     *
     * @mbg.generated Thu Jun 28 18:05:45 CST 2018
     */
    List<ShopStorage> selectByExample(ShopStorageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_storage
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    ShopStorage selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") ShopStorage.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_storage
     *
     * @mbg.generated Thu Jun 28 18:05:45 CST 2018
     */
    ShopStorage selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_storage
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    ShopStorage selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_storage
     *
     * @mbg.generated Thu Jun 28 18:05:45 CST 2018
     */
    int updateByExampleSelective(@Param("record") ShopStorage record, @Param("example") ShopStorageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_storage
     *
     * @mbg.generated Thu Jun 28 18:05:45 CST 2018
     */
    int updateByExample(@Param("record") ShopStorage record, @Param("example") ShopStorageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_storage
     *
     * @mbg.generated Thu Jun 28 18:05:45 CST 2018
     */
    int updateByPrimaryKeySelective(ShopStorage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_storage
     *
     * @mbg.generated Thu Jun 28 18:05:45 CST 2018
     */
    int updateByPrimaryKey(ShopStorage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_storage
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByExample(@Param("example") ShopStorageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_storage
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByPrimaryKey(Integer id);
}