package manman.pro.db.dao;

import java.util.List;
import manman.pro.db.domain.ShopCollect;
import manman.pro.db.domain.ShopCollectExample;
import org.apache.ibatis.annotations.Param;

public interface ShopCollectMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_collect
     *
     * @mbg.generated Thu Jun 28 18:05:45 CST 2018
     */
    long countByExample(ShopCollectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_collect
     *
     * @mbg.generated Thu Jun 28 18:05:45 CST 2018
     */
    int deleteByExample(ShopCollectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_collect
     *
     * @mbg.generated Thu Jun 28 18:05:45 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_collect
     *
     * @mbg.generated Thu Jun 28 18:05:45 CST 2018
     */
    int insert(ShopCollect record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_collect
     *
     * @mbg.generated Thu Jun 28 18:05:45 CST 2018
     */
    int insertSelective(ShopCollect record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_collect
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    ShopCollect selectOneByExample(ShopCollectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_collect
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    ShopCollect selectOneByExampleSelective(@Param("example") ShopCollectExample example, @Param("selective") ShopCollect.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_collect
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    List<ShopCollect> selectByExampleSelective(@Param("example") ShopCollectExample example, @Param("selective") ShopCollect.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_collect
     *
     * @mbg.generated Thu Jun 28 18:05:45 CST 2018
     */
    List<ShopCollect> selectByExample(ShopCollectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_collect
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    ShopCollect selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") ShopCollect.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_collect
     *
     * @mbg.generated Thu Jun 28 18:05:45 CST 2018
     */
    ShopCollect selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_collect
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    ShopCollect selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_collect
     *
     * @mbg.generated Thu Jun 28 18:05:45 CST 2018
     */
    int updateByExampleSelective(@Param("record") ShopCollect record, @Param("example") ShopCollectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_collect
     *
     * @mbg.generated Thu Jun 28 18:05:45 CST 2018
     */
    int updateByExample(@Param("record") ShopCollect record, @Param("example") ShopCollectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_collect
     *
     * @mbg.generated Thu Jun 28 18:05:45 CST 2018
     */
    int updateByPrimaryKeySelective(ShopCollect record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_collect
     *
     * @mbg.generated Thu Jun 28 18:05:45 CST 2018
     */
    int updateByPrimaryKey(ShopCollect record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_collect
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByExample(@Param("example") ShopCollectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_collect
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByPrimaryKey(Integer id);
}