package manman.pro.db.dao;

import java.util.List;
import manman.pro.db.domain.ShopRegion;
import manman.pro.db.domain.ShopRegionExample;
import org.apache.ibatis.annotations.Param;

public interface ShopRegionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_region
     *
     * @mbg.generated Thu Jun 28 18:05:45 CST 2018
     */
    long countByExample(ShopRegionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_region
     *
     * @mbg.generated Thu Jun 28 18:05:45 CST 2018
     */
    int deleteByExample(ShopRegionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_region
     *
     * @mbg.generated Thu Jun 28 18:05:45 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_region
     *
     * @mbg.generated Thu Jun 28 18:05:45 CST 2018
     */
    int insert(ShopRegion record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_region
     *
     * @mbg.generated Thu Jun 28 18:05:45 CST 2018
     */
    int insertSelective(ShopRegion record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_region
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    ShopRegion selectOneByExample(ShopRegionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_region
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    ShopRegion selectOneByExampleSelective(@Param("example") ShopRegionExample example, @Param("selective") ShopRegion.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_region
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    List<ShopRegion> selectByExampleSelective(@Param("example") ShopRegionExample example, @Param("selective") ShopRegion.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_region
     *
     * @mbg.generated Thu Jun 28 18:05:45 CST 2018
     */
    List<ShopRegion> selectByExample(ShopRegionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_region
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    ShopRegion selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") ShopRegion.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_region
     *
     * @mbg.generated Thu Jun 28 18:05:45 CST 2018
     */
    ShopRegion selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_region
     *
     * @mbg.generated Thu Jun 28 18:05:45 CST 2018
     */
    int updateByExampleSelective(@Param("record") ShopRegion record, @Param("example") ShopRegionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_region
     *
     * @mbg.generated Thu Jun 28 18:05:45 CST 2018
     */
    int updateByExample(@Param("record") ShopRegion record, @Param("example") ShopRegionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_region
     *
     * @mbg.generated Thu Jun 28 18:05:45 CST 2018
     */
    int updateByPrimaryKeySelective(ShopRegion record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_region
     *
     * @mbg.generated Thu Jun 28 18:05:45 CST 2018
     */
    int updateByPrimaryKey(ShopRegion record);
}