package manman.pro.db.dao;

import java.util.List;
import manman.pro.db.domain.ShopIssue;
import manman.pro.db.domain.ShopIssueExample;
import org.apache.ibatis.annotations.Param;

public interface ShopIssueMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_issue
     *
     * @mbg.generated Thu Jun 28 18:05:45 CST 2018
     */
    long countByExample(ShopIssueExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_issue
     *
     * @mbg.generated Thu Jun 28 18:05:45 CST 2018
     */
    int deleteByExample(ShopIssueExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_issue
     *
     * @mbg.generated Thu Jun 28 18:05:45 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_issue
     *
     * @mbg.generated Thu Jun 28 18:05:45 CST 2018
     */
    int insert(ShopIssue record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_issue
     *
     * @mbg.generated Thu Jun 28 18:05:45 CST 2018
     */
    int insertSelective(ShopIssue record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_issue
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    ShopIssue selectOneByExample(ShopIssueExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_issue
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    ShopIssue selectOneByExampleSelective(@Param("example") ShopIssueExample example, @Param("selective") ShopIssue.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_issue
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    List<ShopIssue> selectByExampleSelective(@Param("example") ShopIssueExample example, @Param("selective") ShopIssue.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_issue
     *
     * @mbg.generated Thu Jun 28 18:05:45 CST 2018
     */
    List<ShopIssue> selectByExample(ShopIssueExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_issue
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    ShopIssue selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") ShopIssue.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_issue
     *
     * @mbg.generated Thu Jun 28 18:05:45 CST 2018
     */
    ShopIssue selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_issue
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    ShopIssue selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_issue
     *
     * @mbg.generated Thu Jun 28 18:05:45 CST 2018
     */
    int updateByExampleSelective(@Param("record") ShopIssue record, @Param("example") ShopIssueExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_issue
     *
     * @mbg.generated Thu Jun 28 18:05:45 CST 2018
     */
    int updateByExample(@Param("record") ShopIssue record, @Param("example") ShopIssueExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_issue
     *
     * @mbg.generated Thu Jun 28 18:05:45 CST 2018
     */
    int updateByPrimaryKeySelective(ShopIssue record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_issue
     *
     * @mbg.generated Thu Jun 28 18:05:45 CST 2018
     */
    int updateByPrimaryKey(ShopIssue record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_issue
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByExample(@Param("example") ShopIssueExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_issue
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByPrimaryKey(Integer id);
}