package manman.pro.db.dao;

import java.util.List;
import manman.pro.db.domain.ShopAd;
import manman.pro.db.domain.ShopAdExample;
import org.apache.ibatis.annotations.Param;

public interface ShopAdMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_ad
     *
     * @mbg.generated Thu Jun 28 18:05:45 CST 2018
     */
    long countByExample(ShopAdExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_ad
     *
     * @mbg.generated Thu Jun 28 18:05:45 CST 2018
     */
    int deleteByExample(ShopAdExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_ad
     *
     * @mbg.generated Thu Jun 28 18:05:45 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_ad
     *
     * @mbg.generated Thu Jun 28 18:05:45 CST 2018
     */
    int insert(ShopAd record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_ad
     *
     * @mbg.generated Thu Jun 28 18:05:45 CST 2018
     */
    int insertSelective(ShopAd record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_ad
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    ShopAd selectOneByExample(ShopAdExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_ad
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    ShopAd selectOneByExampleSelective(@Param("example") ShopAdExample example, @Param("selective") ShopAd.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_ad
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    List<ShopAd> selectByExampleSelective(@Param("example") ShopAdExample example, @Param("selective") ShopAd.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_ad
     *
     * @mbg.generated Thu Jun 28 18:05:45 CST 2018
     */
    List<ShopAd> selectByExample(ShopAdExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_ad
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    ShopAd selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") ShopAd.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_ad
     *
     * @mbg.generated Thu Jun 28 18:05:45 CST 2018
     */
    ShopAd selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_ad
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    ShopAd selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_ad
     *
     * @mbg.generated Thu Jun 28 18:05:45 CST 2018
     */
    int updateByExampleSelective(@Param("record") ShopAd record, @Param("example") ShopAdExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_ad
     *
     * @mbg.generated Thu Jun 28 18:05:45 CST 2018
     */
    int updateByExample(@Param("record") ShopAd record, @Param("example") ShopAdExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_ad
     *
     * @mbg.generated Thu Jun 28 18:05:45 CST 2018
     */
    int updateByPrimaryKeySelective(ShopAd record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_ad
     *
     * @mbg.generated Thu Jun 28 18:05:45 CST 2018
     */
    int updateByPrimaryKey(ShopAd record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_ad
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByExample(@Param("example") ShopAdExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_ad
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByPrimaryKey(Integer id);
}