package manman.pro.db.dao;

import java.util.List;
import manman.pro.db.domain.ShopBrand;
import manman.pro.db.domain.ShopBrandExample;
import org.apache.ibatis.annotations.Param;

public interface ShopBrandMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_brand
     *
     * @mbg.generated Thu Jun 28 18:05:45 CST 2018
     */
    long countByExample(ShopBrandExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_brand
     *
     * @mbg.generated Thu Jun 28 18:05:45 CST 2018
     */
    int deleteByExample(ShopBrandExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_brand
     *
     * @mbg.generated Thu Jun 28 18:05:45 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_brand
     *
     * @mbg.generated Thu Jun 28 18:05:45 CST 2018
     */
    int insert(ShopBrand record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_brand
     *
     * @mbg.generated Thu Jun 28 18:05:45 CST 2018
     */
    int insertSelective(ShopBrand record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_brand
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    ShopBrand selectOneByExample(ShopBrandExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_brand
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    ShopBrand selectOneByExampleSelective(@Param("example") ShopBrandExample example, @Param("selective") ShopBrand.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_brand
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    List<ShopBrand> selectByExampleSelective(@Param("example") ShopBrandExample example, @Param("selective") ShopBrand.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_brand
     *
     * @mbg.generated Thu Jun 28 18:05:45 CST 2018
     */
    List<ShopBrand> selectByExample(ShopBrandExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_brand
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    ShopBrand selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") ShopBrand.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_brand
     *
     * @mbg.generated Thu Jun 28 18:05:45 CST 2018
     */
    ShopBrand selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_brand
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    ShopBrand selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_brand
     *
     * @mbg.generated Thu Jun 28 18:05:45 CST 2018
     */
    int updateByExampleSelective(@Param("record") ShopBrand record, @Param("example") ShopBrandExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_brand
     *
     * @mbg.generated Thu Jun 28 18:05:45 CST 2018
     */
    int updateByExample(@Param("record") ShopBrand record, @Param("example") ShopBrandExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_brand
     *
     * @mbg.generated Thu Jun 28 18:05:45 CST 2018
     */
    int updateByPrimaryKeySelective(ShopBrand record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_brand
     *
     * @mbg.generated Thu Jun 28 18:05:45 CST 2018
     */
    int updateByPrimaryKey(ShopBrand record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_brand
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByExample(@Param("example") ShopBrandExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_brand
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByPrimaryKey(Integer id);
}