package manman.pro.db.dao;

import java.util.List;
import manman.pro.db.domain.ShopKeyword;
import manman.pro.db.domain.ShopKeywordExample;
import org.apache.ibatis.annotations.Param;

public interface ShopKeywordMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_keyword
     *
     * @mbg.generated Thu Jun 28 18:05:45 CST 2018
     */
    long countByExample(ShopKeywordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_keyword
     *
     * @mbg.generated Thu Jun 28 18:05:45 CST 2018
     */
    int deleteByExample(ShopKeywordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_keyword
     *
     * @mbg.generated Thu Jun 28 18:05:45 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_keyword
     *
     * @mbg.generated Thu Jun 28 18:05:45 CST 2018
     */
    int insert(ShopKeyword record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_keyword
     *
     * @mbg.generated Thu Jun 28 18:05:45 CST 2018
     */
    int insertSelective(ShopKeyword record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_keyword
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    ShopKeyword selectOneByExample(ShopKeywordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_keyword
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    ShopKeyword selectOneByExampleSelective(@Param("example") ShopKeywordExample example, @Param("selective") ShopKeyword.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_keyword
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    List<ShopKeyword> selectByExampleSelective(@Param("example") ShopKeywordExample example, @Param("selective") ShopKeyword.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_keyword
     *
     * @mbg.generated Thu Jun 28 18:05:45 CST 2018
     */
    List<ShopKeyword> selectByExample(ShopKeywordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_keyword
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    ShopKeyword selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") ShopKeyword.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_keyword
     *
     * @mbg.generated Thu Jun 28 18:05:45 CST 2018
     */
    ShopKeyword selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_keyword
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    ShopKeyword selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_keyword
     *
     * @mbg.generated Thu Jun 28 18:05:45 CST 2018
     */
    int updateByExampleSelective(@Param("record") ShopKeyword record, @Param("example") ShopKeywordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_keyword
     *
     * @mbg.generated Thu Jun 28 18:05:45 CST 2018
     */
    int updateByExample(@Param("record") ShopKeyword record, @Param("example") ShopKeywordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_keyword
     *
     * @mbg.generated Thu Jun 28 18:05:45 CST 2018
     */
    int updateByPrimaryKeySelective(ShopKeyword record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_keyword
     *
     * @mbg.generated Thu Jun 28 18:05:45 CST 2018
     */
    int updateByPrimaryKey(ShopKeyword record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_keyword
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByExample(@Param("example") ShopKeywordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_keyword
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByPrimaryKey(Integer id);
}