package manman.pro.db.dao;

import java.util.List;
import manman.pro.db.domain.ShopComment;
import manman.pro.db.domain.ShopCommentExample;
import org.apache.ibatis.annotations.Param;

public interface ShopCommentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_comment
     *
     * @mbg.generated Thu Jun 28 18:05:45 CST 2018
     */
    long countByExample(ShopCommentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_comment
     *
     * @mbg.generated Thu Jun 28 18:05:45 CST 2018
     */
    int deleteByExample(ShopCommentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_comment
     *
     * @mbg.generated Thu Jun 28 18:05:45 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_comment
     *
     * @mbg.generated Thu Jun 28 18:05:45 CST 2018
     */
    int insert(ShopComment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_comment
     *
     * @mbg.generated Thu Jun 28 18:05:45 CST 2018
     */
    int insertSelective(ShopComment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_comment
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    ShopComment selectOneByExample(ShopCommentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_comment
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    ShopComment selectOneByExampleSelective(@Param("example") ShopCommentExample example, @Param("selective") ShopComment.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_comment
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    List<ShopComment> selectByExampleSelective(@Param("example") ShopCommentExample example, @Param("selective") ShopComment.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_comment
     *
     * @mbg.generated Thu Jun 28 18:05:45 CST 2018
     */
    List<ShopComment> selectByExample(ShopCommentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_comment
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    ShopComment selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") ShopComment.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_comment
     *
     * @mbg.generated Thu Jun 28 18:05:45 CST 2018
     */
    ShopComment selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_comment
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    ShopComment selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_comment
     *
     * @mbg.generated Thu Jun 28 18:05:45 CST 2018
     */
    int updateByExampleSelective(@Param("record") ShopComment record, @Param("example") ShopCommentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_comment
     *
     * @mbg.generated Thu Jun 28 18:05:45 CST 2018
     */
    int updateByExample(@Param("record") ShopComment record, @Param("example") ShopCommentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_comment
     *
     * @mbg.generated Thu Jun 28 18:05:45 CST 2018
     */
    int updateByPrimaryKeySelective(ShopComment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_comment
     *
     * @mbg.generated Thu Jun 28 18:05:45 CST 2018
     */
    int updateByPrimaryKey(ShopComment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_comment
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByExample(@Param("example") ShopCommentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_comment
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByPrimaryKey(Integer id);
}